---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  require_chef_omnibus: 13.6.4
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows10pro
    driver:
      name: hieunb/windows10pro
    transport:
      name: winrm 

suites:
  - name: default
    run_list:
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
